// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthenticationService/UserService.proto

package naviauthentication;

public final class UserService {
  private UserService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'AuthenticationService/UserService.prot" +
      "o\022\022naviauthentication\0320AuthenticationSer" +
      "vice/CommunicationMessage.proto2\254\001\n\016Auth" +
      "entication\022O\n\014RegisterUser\022#.naviauthent" +
      "ication.RegisterRequest\032\032.naviauthentica" +
      "tion.Result\022I\n\tLoginUser\022 .naviauthentic" +
      "ation.LoginRequest\032\032.naviauthentication." +
      "ResultB\033\252\002\030NaviAuthenticationSharedb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          naviauthentication.CommunicationMessage.getDescriptor(),
        });
    naviauthentication.CommunicationMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
