// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService/StorageMessage.proto

package navistorage;

public final class StorageMessage {
  private StorageMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FindInsideFilesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:navistorage.FindInsideFilesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userEmail = 1;</code>
     * @return The userEmail.
     */
    java.lang.String getUserEmail();
    /**
     * <code>string userEmail = 1;</code>
     * @return The bytes for userEmail.
     */
    com.google.protobuf.ByteString
        getUserEmailBytes();

    /**
     * <code>string targetFolder = 2;</code>
     * @return The targetFolder.
     */
    java.lang.String getTargetFolder();
    /**
     * <code>string targetFolder = 2;</code>
     * @return The bytes for targetFolder.
     */
    com.google.protobuf.ByteString
        getTargetFolderBytes();
  }
  /**
   * <pre>
   * Messgae for request files in the folder
   * </pre>
   *
   * Protobuf type {@code navistorage.FindInsideFilesRequest}
   */
  public static final class FindInsideFilesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:navistorage.FindInsideFilesRequest)
      FindInsideFilesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindInsideFilesRequest.newBuilder() to construct.
    private FindInsideFilesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindInsideFilesRequest() {
      userEmail_ = "";
      targetFolder_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FindInsideFilesRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindInsideFilesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userEmail_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              targetFolder_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return navistorage.StorageMessage.internal_static_navistorage_FindInsideFilesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return navistorage.StorageMessage.internal_static_navistorage_FindInsideFilesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              navistorage.StorageMessage.FindInsideFilesRequest.class, navistorage.StorageMessage.FindInsideFilesRequest.Builder.class);
    }

    public static final int USEREMAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object userEmail_;
    /**
     * <code>string userEmail = 1;</code>
     * @return The userEmail.
     */
    @java.lang.Override
    public java.lang.String getUserEmail() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userEmail_ = s;
        return s;
      }
    }
    /**
     * <code>string userEmail = 1;</code>
     * @return The bytes for userEmail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGETFOLDER_FIELD_NUMBER = 2;
    private volatile java.lang.Object targetFolder_;
    /**
     * <code>string targetFolder = 2;</code>
     * @return The targetFolder.
     */
    @java.lang.Override
    public java.lang.String getTargetFolder() {
      java.lang.Object ref = targetFolder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetFolder_ = s;
        return s;
      }
    }
    /**
     * <code>string targetFolder = 2;</code>
     * @return The bytes for targetFolder.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetFolderBytes() {
      java.lang.Object ref = targetFolder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetFolder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userEmail_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetFolder_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, targetFolder_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userEmail_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetFolder_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, targetFolder_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof navistorage.StorageMessage.FindInsideFilesRequest)) {
        return super.equals(obj);
      }
      navistorage.StorageMessage.FindInsideFilesRequest other = (navistorage.StorageMessage.FindInsideFilesRequest) obj;

      if (!getUserEmail()
          .equals(other.getUserEmail())) return false;
      if (!getTargetFolder()
          .equals(other.getTargetFolder())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USEREMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getUserEmail().hashCode();
      hash = (37 * hash) + TARGETFOLDER_FIELD_NUMBER;
      hash = (53 * hash) + getTargetFolder().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static navistorage.StorageMessage.FindInsideFilesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(navistorage.StorageMessage.FindInsideFilesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Messgae for request files in the folder
     * </pre>
     *
     * Protobuf type {@code navistorage.FindInsideFilesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:navistorage.FindInsideFilesRequest)
        navistorage.StorageMessage.FindInsideFilesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return navistorage.StorageMessage.internal_static_navistorage_FindInsideFilesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return navistorage.StorageMessage.internal_static_navistorage_FindInsideFilesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                navistorage.StorageMessage.FindInsideFilesRequest.class, navistorage.StorageMessage.FindInsideFilesRequest.Builder.class);
      }

      // Construct using navistorage.StorageMessage.FindInsideFilesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userEmail_ = "";

        targetFolder_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return navistorage.StorageMessage.internal_static_navistorage_FindInsideFilesRequest_descriptor;
      }

      @java.lang.Override
      public navistorage.StorageMessage.FindInsideFilesRequest getDefaultInstanceForType() {
        return navistorage.StorageMessage.FindInsideFilesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public navistorage.StorageMessage.FindInsideFilesRequest build() {
        navistorage.StorageMessage.FindInsideFilesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public navistorage.StorageMessage.FindInsideFilesRequest buildPartial() {
        navistorage.StorageMessage.FindInsideFilesRequest result = new navistorage.StorageMessage.FindInsideFilesRequest(this);
        result.userEmail_ = userEmail_;
        result.targetFolder_ = targetFolder_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof navistorage.StorageMessage.FindInsideFilesRequest) {
          return mergeFrom((navistorage.StorageMessage.FindInsideFilesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(navistorage.StorageMessage.FindInsideFilesRequest other) {
        if (other == navistorage.StorageMessage.FindInsideFilesRequest.getDefaultInstance()) return this;
        if (!other.getUserEmail().isEmpty()) {
          userEmail_ = other.userEmail_;
          onChanged();
        }
        if (!other.getTargetFolder().isEmpty()) {
          targetFolder_ = other.targetFolder_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        navistorage.StorageMessage.FindInsideFilesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (navistorage.StorageMessage.FindInsideFilesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userEmail_ = "";
      /**
       * <code>string userEmail = 1;</code>
       * @return The userEmail.
       */
      public java.lang.String getUserEmail() {
        java.lang.Object ref = userEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userEmail = 1;</code>
       * @return The bytes for userEmail.
       */
      public com.google.protobuf.ByteString
          getUserEmailBytes() {
        java.lang.Object ref = userEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userEmail = 1;</code>
       * @param value The userEmail to set.
       * @return This builder for chaining.
       */
      public Builder setUserEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userEmail = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserEmail() {
        
        userEmail_ = getDefaultInstance().getUserEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string userEmail = 1;</code>
       * @param value The bytes for userEmail to set.
       * @return This builder for chaining.
       */
      public Builder setUserEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userEmail_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object targetFolder_ = "";
      /**
       * <code>string targetFolder = 2;</code>
       * @return The targetFolder.
       */
      public java.lang.String getTargetFolder() {
        java.lang.Object ref = targetFolder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetFolder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string targetFolder = 2;</code>
       * @return The bytes for targetFolder.
       */
      public com.google.protobuf.ByteString
          getTargetFolderBytes() {
        java.lang.Object ref = targetFolder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetFolder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string targetFolder = 2;</code>
       * @param value The targetFolder to set.
       * @return This builder for chaining.
       */
      public Builder setTargetFolder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetFolder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string targetFolder = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetFolder() {
        
        targetFolder_ = getDefaultInstance().getTargetFolder();
        onChanged();
        return this;
      }
      /**
       * <code>string targetFolder = 2;</code>
       * @param value The bytes for targetFolder to set.
       * @return This builder for chaining.
       */
      public Builder setTargetFolderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        targetFolder_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:navistorage.FindInsideFilesRequest)
    }

    // @@protoc_insertion_point(class_scope:navistorage.FindInsideFilesRequest)
    private static final navistorage.StorageMessage.FindInsideFilesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new navistorage.StorageMessage.FindInsideFilesRequest();
    }

    public static navistorage.StorageMessage.FindInsideFilesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindInsideFilesRequest>
        PARSER = new com.google.protobuf.AbstractParser<FindInsideFilesRequest>() {
      @java.lang.Override
      public FindInsideFilesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindInsideFilesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindInsideFilesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindInsideFilesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public navistorage.StorageMessage.FindInsideFilesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateRootFolderRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:navistorage.CreateRootFolderRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Only user email is needed, and Result should be used.
     * </pre>
     *
     * <code>string userEmail = 1;</code>
     * @return The userEmail.
     */
    java.lang.String getUserEmail();
    /**
     * <pre>
     * Only user email is needed, and Result should be used.
     * </pre>
     *
     * <code>string userEmail = 1;</code>
     * @return The bytes for userEmail.
     */
    com.google.protobuf.ByteString
        getUserEmailBytes();
  }
  /**
   * <pre>
   * Message For requesting root-folder creation
   * </pre>
   *
   * Protobuf type {@code navistorage.CreateRootFolderRequest}
   */
  public static final class CreateRootFolderRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:navistorage.CreateRootFolderRequest)
      CreateRootFolderRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateRootFolderRequest.newBuilder() to construct.
    private CreateRootFolderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateRootFolderRequest() {
      userEmail_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateRootFolderRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateRootFolderRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userEmail_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return navistorage.StorageMessage.internal_static_navistorage_CreateRootFolderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return navistorage.StorageMessage.internal_static_navistorage_CreateRootFolderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              navistorage.StorageMessage.CreateRootFolderRequest.class, navistorage.StorageMessage.CreateRootFolderRequest.Builder.class);
    }

    public static final int USEREMAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object userEmail_;
    /**
     * <pre>
     * Only user email is needed, and Result should be used.
     * </pre>
     *
     * <code>string userEmail = 1;</code>
     * @return The userEmail.
     */
    @java.lang.Override
    public java.lang.String getUserEmail() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userEmail_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Only user email is needed, and Result should be used.
     * </pre>
     *
     * <code>string userEmail = 1;</code>
     * @return The bytes for userEmail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userEmail_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userEmail_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof navistorage.StorageMessage.CreateRootFolderRequest)) {
        return super.equals(obj);
      }
      navistorage.StorageMessage.CreateRootFolderRequest other = (navistorage.StorageMessage.CreateRootFolderRequest) obj;

      if (!getUserEmail()
          .equals(other.getUserEmail())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USEREMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getUserEmail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static navistorage.StorageMessage.CreateRootFolderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(navistorage.StorageMessage.CreateRootFolderRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message For requesting root-folder creation
     * </pre>
     *
     * Protobuf type {@code navistorage.CreateRootFolderRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:navistorage.CreateRootFolderRequest)
        navistorage.StorageMessage.CreateRootFolderRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return navistorage.StorageMessage.internal_static_navistorage_CreateRootFolderRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return navistorage.StorageMessage.internal_static_navistorage_CreateRootFolderRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                navistorage.StorageMessage.CreateRootFolderRequest.class, navistorage.StorageMessage.CreateRootFolderRequest.Builder.class);
      }

      // Construct using navistorage.StorageMessage.CreateRootFolderRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userEmail_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return navistorage.StorageMessage.internal_static_navistorage_CreateRootFolderRequest_descriptor;
      }

      @java.lang.Override
      public navistorage.StorageMessage.CreateRootFolderRequest getDefaultInstanceForType() {
        return navistorage.StorageMessage.CreateRootFolderRequest.getDefaultInstance();
      }

      @java.lang.Override
      public navistorage.StorageMessage.CreateRootFolderRequest build() {
        navistorage.StorageMessage.CreateRootFolderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public navistorage.StorageMessage.CreateRootFolderRequest buildPartial() {
        navistorage.StorageMessage.CreateRootFolderRequest result = new navistorage.StorageMessage.CreateRootFolderRequest(this);
        result.userEmail_ = userEmail_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof navistorage.StorageMessage.CreateRootFolderRequest) {
          return mergeFrom((navistorage.StorageMessage.CreateRootFolderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(navistorage.StorageMessage.CreateRootFolderRequest other) {
        if (other == navistorage.StorageMessage.CreateRootFolderRequest.getDefaultInstance()) return this;
        if (!other.getUserEmail().isEmpty()) {
          userEmail_ = other.userEmail_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        navistorage.StorageMessage.CreateRootFolderRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (navistorage.StorageMessage.CreateRootFolderRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userEmail_ = "";
      /**
       * <pre>
       * Only user email is needed, and Result should be used.
       * </pre>
       *
       * <code>string userEmail = 1;</code>
       * @return The userEmail.
       */
      public java.lang.String getUserEmail() {
        java.lang.Object ref = userEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Only user email is needed, and Result should be used.
       * </pre>
       *
       * <code>string userEmail = 1;</code>
       * @return The bytes for userEmail.
       */
      public com.google.protobuf.ByteString
          getUserEmailBytes() {
        java.lang.Object ref = userEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Only user email is needed, and Result should be used.
       * </pre>
       *
       * <code>string userEmail = 1;</code>
       * @param value The userEmail to set.
       * @return This builder for chaining.
       */
      public Builder setUserEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Only user email is needed, and Result should be used.
       * </pre>
       *
       * <code>string userEmail = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserEmail() {
        
        userEmail_ = getDefaultInstance().getUserEmail();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Only user email is needed, and Result should be used.
       * </pre>
       *
       * <code>string userEmail = 1;</code>
       * @param value The bytes for userEmail to set.
       * @return This builder for chaining.
       */
      public Builder setUserEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userEmail_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:navistorage.CreateRootFolderRequest)
    }

    // @@protoc_insertion_point(class_scope:navistorage.CreateRootFolderRequest)
    private static final navistorage.StorageMessage.CreateRootFolderRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new navistorage.StorageMessage.CreateRootFolderRequest();
    }

    public static navistorage.StorageMessage.CreateRootFolderRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateRootFolderRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateRootFolderRequest>() {
      @java.lang.Override
      public CreateRootFolderRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateRootFolderRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateRootFolderRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateRootFolderRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public navistorage.StorageMessage.CreateRootFolderRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_navistorage_FindInsideFilesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_navistorage_FindInsideFilesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_navistorage_CreateRootFolderRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_navistorage_CreateRootFolderRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#StorageService/StorageMessage.proto\022\013n" +
      "avistorage\"A\n\026FindInsideFilesRequest\022\021\n\t" +
      "userEmail\030\001 \001(\t\022\024\n\014targetFolder\030\002 \001(\t\",\n" +
      "\027CreateRootFolderRequest\022\021\n\tuserEmail\030\001 " +
      "\001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_navistorage_FindInsideFilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_navistorage_FindInsideFilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_navistorage_FindInsideFilesRequest_descriptor,
        new java.lang.String[] { "UserEmail", "TargetFolder", });
    internal_static_navistorage_CreateRootFolderRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_navistorage_CreateRootFolderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_navistorage_CreateRootFolderRequest_descriptor,
        new java.lang.String[] { "UserEmail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
